### ISSUE TITLE
'gulp dev' error

### ISSUE THREAD

**Issue by juha-h** [versatica/tryit-jssip#19]
Building the app with 'gulp dev' gave an error:
```
$ gulp dev
[11:05:35] Using gulpfile /usr/src/orig/tryit-jssip/gulpfile.js
[11:05:35] Starting 'dev'...
[11:05:35] Starting 'env:dev'...
[11:05:35] setting "dev" environment
[11:05:35] Finished 'env:dev' after 3.5 ms
[11:05:35] Starting 'clean'...
[11:05:35] Finished 'clean' after 8.88 ms
[11:05:35] Starting 'lint'...
[11:05:36] Finished 'lint' after 1.29 s
[11:05:36] Starting 'bundle'...
[11:05:44] Finished 'bundle' after 8.35 s
[11:05:44] Starting 'html'...
[11:05:44] Finished 'html' after 6.27 ms
[11:05:44] Starting 'css'...
[11:05:45] Plumber found unhandled error:
 TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[11:05:45] Finished 'css' after 746 ms
[11:05:45] Starting 'resources'...
[11:05:45] Finished 'resources' after 14 ms
[11:05:45] Finished 'dev' after 10 s
```
Don't know yet if it is a fatal one.

**Comment by ibc** [comment]
You have changed the version of `gulp` in package.json so it now installs gulp 3.9.1 which is old API.

**Comment by ibc** [comment]
The package.json issue is fixed now in master. It happened because gulp guys have deleted "4.0" branch.

**Comment by juha-h** [comment]
Iñaki Baz Castillo writes:

> The package.json issue is fixed now in master. It happened because
> gulp guys have deleted "4.0" branch.

Thanks for the fix, Juha

**Comment by juha-h** [comment]
Sorry, but I need to reopen this.  I checked that my gulp versions match those in package.json, but I still get the above error.

In package.json:
```
$ grep gulp package.json
    "gulp": "^4.0.0",
    "gulp-css-base64": "^1.3.4",
    "gulp-eslint": "^5.0.0",
    "gulp-header": "^2.0.5",
    "gulp-if": "^2.0.2",
    "gulp-plumber": "^1.2.0",
    "gulp-rename": "^1.4.0",
    "gulp-stylus": "^2.7.0",
    "gulp-touch": "^1.0.1",
    "gulp-uglify-es": "^1.0.4",
    "gulp-util": "^3.0.8",
```
On my host:
```
$ npm list | grep gulp
├─┬ gulp@4.0.0
│ ├─┬ gulp-cli@2.0.1
│ │ ├── gulplog@1.0.0 deduped
├─┬ gulp-css-base64@1.3.4
│ ├── gulp-util@3.0.8 deduped
├─┬ gulp-eslint@5.0.0
├─┬ gulp-header@2.0.5
├─┬ gulp-if@2.0.2
│ ├─┬ gulp-match@1.0.3
├─┬ gulp-plumber@1.2.0
├── gulp-rename@1.4.0
├─┬ gulp-stylus@2.7.0
├─┬ gulp-touch@1.0.1
├─┬ gulp-uglify-es@1.0.4
├─┬ gulp-util@3.0.8
```

**Comment by ibc** [comment]
Indeed, a wrong dep `gulp-touch` that was inmaintained and produces an error in Node 10. Fixed. Thanks.

b154086186d420dd4f6d2e38e3a61f34882a8644
